name: spac-scimap-testing
channels:
  - ohsu-comp-bio
  - conda-forge
  - leej3
dependencies:
  - python=3.10.15
  - pip
  - matplotlib
  - anndata
  - scikit-learn
  - squidpy
  - numpy
  - scikit-learn
  - seaborn
  - scanpy
  - pandas
  - plotly
  - cookiecutter
  - datashader
  - numba
  - Pillow
  - zarr
  - pip:
    - phenograph==1.5.7
    - pylint
    - pytest
    - sphinx
    - flake8
    - gendocs
    - scimap==2.1.3
